project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true
pull_request_title: "[translation] Update translation from Crowdin"
files:
  - source: "**/values/strings.xml"
    translation: "**/values-%two_letters_code%/%original_file_name%"
    languages_mapping:
      two_letters_code:
        he: "iw"

